### ISSUE TITLE
Design and implement the API endpoint(s) for sending and receiving chat messages

### ISSUE THREAD

**Issue by Js18x** [sopra-fs24-group-6/Server#97]

**Comment by kmkm0113** [comment]
622f6ea7628dac88fa7e1b6ef678ce805df5881c

**Comment by kmkm0113** [comment]
622f6ea7628dac88fa7e1b6ef678ce805df5881c

**Comment by kmkm0113** [comment]
https://github.com/sopra-fs24-group-6/Client/commit/622f6ea7628dac88fa7e1b6ef678ce805df5881c
